import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int numOfFamilies = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		double sumChildrenForAllFamilies = 0;
		for (int family = 0; family < numOfFamilies; family++)
		{
			boolean haveBoy = false;
			boolean haveGirl = false;
			int childrenForThisFamily= 0;
			while (!(haveBoy && haveGirl)) {
				double rnd = generator.nextDouble();
				if (rnd < 0.5) {
					haveBoy = true;
				} else {
					haveGirl = true;
				}
				childrenForThisFamily++;
			}
			sumChildrenForAllFamilies += childrenForThisFamily;
		}
		double averageChildren = sumChildrenForAllFamilies / numOfFamilies;
		System.out.println("Average: " + averageChildren + " children to get at least one of each gender.");

		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
